name: Deploy to Cloud Run

on:
  workflow_dispatch:
  push:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  IMAGE: ${{ secrets.GCP_IMAGE }}
  REGION: ${{ secrets.GCP_REGION }}
  TAG: latest

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy.
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCLOUD_AUTH }}"

      - name: Setup Google Cloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCLOUD_AUTH }}
          project_id: ${{ secrets.PROJECT_ID }}

      - name: Configure Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and push
        run: |
          docker build --platform linux/amd64 -t us-central1-docker.pkg.dev/$PROJECT_ID/$IMAGE:$TAG .
          docker push us-central1-docker.pkg.dev/$PROJECT_ID/$IMAGE:$TAG

      - name: Deploy
        run: gcloud run deploy $SERVICE_NAME --image us-central1-docker.pkg.dev/$PROJECT_ID/$IMAGE:$TAG --platform managed --region $REGION --allow-unauthenticated
